### ISSUE TITLE
Argument 2 passed to BackupProcedure::run() must be of the type array, string given

### ISSUE THREAD

**Issue by devonzara** [backup-manager/laravel-4#45]
After taking care of #44, I'm still blocked on:

> [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Type error: Argument 2 passed to BackupManager\Procedures\BackupProcedure::run() must be of the type array, string given, called in /home/vagrant/Code/Acme/vendor/backup-manager/laravel/src/DbBackupCommand.php on line 93

I'm not sure how important that cast to array is on previous versions, so I'll let someone else take a look at this. :)

**Comment by whoacowboy** [comment]
I updated and I am still getting this error when I run

`php /home/forge/example.com/current/artisan db:backup --database=mysql --destination=dropbox --destinationPath=`date +\%Y/%d-%m-%Y`--compression=gzip`

from the command line.

**Comment by mitchellvanw** [comment]
Thanks! I've merged a PR that fixes this.

**Comment by driesvints** [comment]
Updated to the latest version (1.1.1) and I'm still getting this. The api seems to have change from 

```
public function run($database, $destination, $destinationPath, $compression);
```

To

```
public function run($database, array $destinations, $compression)
```

Which happened in this commit: https://github.com/backup-manager/backup-manager/commit/533c547ccac6627b28c9afbe93527cc576d990b6

I know that it doesn't explicitly says so anywhere in the readme that this lib is following SemVer but if it does then this should have been tagged as a new major release. The docs also still explain the old api: https://github.com/backup-manager/backup-manager#quick-and-dirty

I've sent in a PR to update the docs: https://github.com/backup-manager/backup-manager/pull/107/
